#!/bin/sh


## Get hardware info
tmp=$( sudo dmidecode )


## Check to see if VMware is listed
if ( echo "${tmp}" | grep -iq vmware ); then
  ## Feedback
  echo "[+] Detected VM (VMware)"

  ## Check to see if Open-VM-Tools is already installed
  if ( dpkg -l | grep -q open-vm-tools ); then
    ## Feedback
    echo "[+] VMware tools is already installed"
  else
    ## Feedback
    echo "[+] Installing VMware tools"

    ## Update repos
    sudo apt-get -qq update \
      || echo -e '\n[-] Issue with apt-get update' 1>&2

    # Install packages
    sudo apt-get -y -qq install open-vm-tools-desktop fuse \
      || echo -e '\n[-] Issue with apt-get install' 1>&2
  fi

  if ! [ -f /usr/local/sbin/mount-shared-folders ]; then
    echo "[+] Adding mount-shared-folders"
    sudo bash -c "cat <<EOF > /usr/local/sbin/mount-shared-folders
#!/bin/sh
vmware-hgfsclient | while read folder; do
  vmwpath=\"/mnt/hgfs/\\\${folder}\"
  echo \"[i] Mounting \\\${folder}   (\\\${vmwpath})\"
  sudo mkdir -p \"\\\${vmwpath}\"
  sudo umount -f \"\\\${vmwpath}\" 2>/dev/null
  sudo vmhgfs-fuse -o allow_other -o auto_unmount \".host:/\\\${folder}\" \"\\\${vmwpath}\"
done
sleep 2s
EOF
"
    sudo chmod +x /usr/local/sbin/mount-shared-folders
  fi

  if ! [ -f /usr/local/sbin/restart-vm-tools ]; then
    echo "[+] Adding restart-vm-tools"
    sudo bash -c "cat <<EOF > /usr/local/sbin/restart-vm-tools
#!/bin/sh
systemctl stop run-vmblock\\\\\\x2dfuse.mount
sudo killall -q -w vmtoolsd
systemctl start run-vmblock\\\\\\x2dfuse.mount
systemctl enable run-vmblock\\\\\\x2dfuse.mount
sudo vmware-user-suid-wrapper vmtoolsd -n vmusr 2>/dev/null
sudo vmtoolsd -b /var/run/vmroot 2>/dev/null
EOF
"
    sudo chmod +x /usr/local/sbin/restart-vm-tools
  fi

elif ( echo "${tmp}" | grep -iq virtualbox ); then
  ## Feedback
  echo "[+] Detected VM (VirtualBox)"

   ## Check to see if Open-VM-Tools is already installed
  if ( dpkg -l | grep -q virtualbox-guest-x11 ); then
    ## Feedback
    echo "[+] VirtualBox's guest additions is already installed"
  else
    ## Feedback
    echo "[+] Installing VirtualBox's guest additions"

    ## Update repos
    sudo apt-get update \
      || echo -e '\n[-] Issue with apt-get update' 1>&2

    # Install packages
    sudo apt-get -y -qq install virtualbox-guest-x11 \
      || echo -e '\n[-] Issue with apt-get install' 1>&2
  fi
fi


echo '[i] Done'
