Document: kali-defaults
Title: Debian kali-defaults Manual
Author: <insert document author here>
Abstract: This manual describes what kali-defaults is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kali-defaults/kali-defaults.sgml.gz

Format: postscript
Files: /usr/share/doc/kali-defaults/kali-defaults.ps.gz

Format: text
Files: /usr/share/doc/kali-defaults/kali-defaults.text.gz

Format: HTML
Index: /usr/share/doc/kali-defaults/html/index.html
Files: /usr/share/doc/kali-defaults/html/*.html
